apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vista-web
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: vista.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vista-web
                port:
                  number: 80
