replicaCount: 1
image:
  repository: ghcr.io/example/vista-web
  tag: "dev"
config:
  NEXT_PUBLIC_API_BASE_URL: "http://vista-backend.default.svc.cluster.local"
  NEXT_PUBLIC_APP_URL: "https://vista-dev.example.com"

ingress:
  enabled: true
  host: vista-dev.example.com
