apiVersion: v1
kind: Service
metadata:
  name: vista-backend
  labels:
    app: vista-backend
spec:
  selector:
    app: vista-backend
  ports:
    - name: http
      port: 80
      targetPort: 4000
  type: ClusterIP
