apiVersion: v1
kind: Secret
metadata:
  name: vista-job-processor-secrets
  labels:
    app: vista-job-processor
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/vista"
