apiVersion: v1
kind: Service
metadata:
  name: {{ include "vista-nats.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: nats
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: nats
  ports:
    - name: client
      port: {{ .Values.service.clientPort }}
      targetPort: client
      protocol: TCP
    - name: monitor
      port: {{ .Values.service.monitorPort }}
      targetPort: monitor
      protocol: TCP