apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vista-nats.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  SURVEYOR_USER: {{ .Values.secrets.SURVEYOR_USER | quote }}
  SURVEYOR_PASSWORD: {{ .Values.secrets.SURVEYOR_PASSWORD | quote }}