apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  NEXT_PUBLIC_API_BASE_URL: {{ .Values.config.NEXT_PUBLIC_API_BASE_URL | quote }}
  NEXT_PUBLIC_APP_URL: {{ .Values.config.NEXT_PUBLIC_APP_URL | quote }}
