global:
  imagePullSecrets:
    - name: gitlab-registry

replicaCount: ${VISTA_POSTGRES_REPLICAS}

image:
  repository: "${POSTGRES_IMAGE_REPOSITORY}"
  tag: "${POSTGRES_IMAGE_TAG}"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

config:
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_DB: "${POSTGRES_DB}"

secrets:
  POSTGRES_PASSWORD: "${POSTGRESQL_PASSWORD}"
  DATABASE_URL: "${DATABASE_URL}"

persistence:
  enabled: true
  storageClass: "${POSTGRES_STORAGE_CLASS}"
  accessMode: ReadWriteOnce
  size: "${POSTGRES_STORAGE_SIZE}"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi
