replicaCount: 1

nameOverride: "postgres"

image:
  repository: pgvector/pgvector
  tag: "pg16"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

config:
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "vista"

secrets:
  POSTGRES_PASSWORD: ""
  DATABASE_URL: ""

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 10Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi
