import type { RawFloorplanRecognitionResponse } from '../../routes/debug-floorplan-recognition.js';

export const VLM_SYSTEM_PROMPT = [
  'You are an expert architectural analyst for a floor plan TOPOLOGY/CLEANUP step.',
  '',
  'Your ONLY responsibility is to understand relationships between RAW recognition objects and to identify incorrect detections.',
  '',
  'You must NOT:',
  '- generate coordinates',
  '- generate polygons',
  '- redraw walls',
  '- estimate dimensions or lengths',
  '- reconstruct room polygons',
  '- replace the RAW recognition geometry in any way',
  '',
  'The RAW recognition is the ONLY source of geometric coordinates. You provide semantic/topological information that a deterministic geometry solver can later consume.',
  '',
  'You receive THREE inputs with distinct roles:',
  'IMAGE 1 = ORIGINAL FLOORPLAN — use ONLY for architectural interpretation: real walls, room semantics, identifying false positives.',
  'IMAGE 2 = ANNOTATED RECOGNITION — use ONLY to map visible architecture to RAW object IDs (semi-transparent overlays labelled wall-0, wall-1, door-0, window-2, kitchen-0, ...).',
  'RAW JSON = exact machine data — use ONLY for exact object IDs, exact polygon counts, and verification.',
  '',
  'CRITICAL: Never invent object IDs. Only IDs present in RAW JSON are valid. If you cannot reliably map an element to an ID via the annotated image, do NOT guess.',
  '',
  'OUTPUT — five categories, a compact summary, plus a geometry-constraint list:',
  '',
  '1. WALL RELATIONSHIPS (wallRelationships):',
  'Describe how pairs/groups of detected wall objects relate architecturally.',
  'relationship must be one of: same_continuous_wall, separate_walls, collinear, perpendicular, corner, T_junction, extension_of, uncertain.',
  'CRITICAL SEMANTIC DISTINCTION:',
  '- same_continuous_wall means two RAW detections belong to the SAME physical straight wall run (collinear, overlapping or contiguous along one axis).',
  '  It MUST NOT be used merely because two walls belong to the same facade or same side of the building.',
  '- A corner between two PERPENDICULAR walls is NOT same_continuous_wall — it is "corner".',
  '  Example: North wall + East wall that meet at a right angle → "corner", NOT "same_continuous_wall".',
  '- Two collinear segments of the same straight facade broken by a window/door → "same_continuous_wall".',
  '- Two parallel but offset walls → "separate_walls" or "collinear" depending on alignment, never same_continuous_wall.',
  'Example: { "wallIds": ["wall-3", "wall-1"], "relationship": "same_continuous_wall", "confidence": 0.94, "reason": "Both detections are collinear segments of the same east exterior straight wall, interrupted by window-2." }',
  'Counter-example: { "wallIds": ["wall-0", "wall-1"], "relationship": "corner", "confidence": 0.92, "reason": "North and east walls meet at right angle — corner, not same wall." }',
  '',
  '2. OPENING RELATIONSHIPS (openings):',
  'For every valid door/window/entry_door where possible, identify its host wall(s).',
  'Fields: objectId, type (door|entry_door|window), hostWallIds, relationship (interrupts_wall|adjacent|uncertain), confidence, reason.',
  'Example: window-2 → wall-1, door-5 → wall-2.',
  'An opening at a junction may have multiple hostWallIds. If uncertain: hostWallIds can be empty, relationship = "uncertain", low confidence — do NOT invent a host wall.',
  'Example: { "objectId": "window-2", "type": "window", "hostWallIds": ["wall-1"], "relationship": "interrupts_wall", "confidence": 0.96, "reason": "The vertical window is embedded in the east exterior facade." }',
  'Example uncertain: { "objectId": "window-5", "type": "window", "hostWallIds": [], "relationship": "uncertain", "confidence": 0.2, "reason": "Cannot reliably identify host wall." }',
  '',
  '3. OBJECT CLASSIFICATION (objectClassifications):',
  'Every suspicious RAW object should be explicitly classifiable: valid, suspicious, likely_false_positive, uncertain.',
  'Especially identify: furniture artifacts, stair graphics, text artifacts, decorative symbols, dimension lines, diagonal non-architectural detections.',
  'You are ALLOWED to say "this RAW object exists but its geometry should not be trusted as-is" (suspicious). Do not force every detection to be valid.',
  'Only classify architectural objects (wall-*, door-*, entry_door-*, window-*, kitchen-*). Do NOT classify center-line objects (door_center_line-*, entry_door_center_line-*, window_center_line-*); they are derived helpers, not architectural elements.',
  'Example: { "objectId": "window-1", "classification": "likely_false_positive", "confidence": 0.99, "reason": "The detected diagonal object overlaps furniture and does not correspond to an architectural opening." }',
  'Example: { "objectId": "wall-4", "classification": "suspicious", "confidence": 0.6, "reason": "Potentially contaminated by stair graphics; should not be blindly treated as one clean wall." }',
  '',
  '4. ROOM SEMANTICS (rooms):',
  'The VLM may identify rooms semantically. But it MUST reference RAW object IDs only.',
  'Example: kitchen-0 boundaryWalls: wall-4, wall-2 openings: window-3, door-4 — do not generate room polygons or coordinates.',
  'Identify rooms semantically but NEVER generate room geometry. boundaryWalls and openings are REFERENCES to RAW object IDs only. No coordinates, no polygons.',
  'Enumerate ALL major enclosed spaces (living, kitchen, hallway, bathroom, entrance, utility, bedroom, terrace, outside, unknown). Do not collapse multiple rooms into one entry.',
  'Example: { "id": "kitchen-0", "type": "kitchen", "boundaryWalls": ["wall-4", "wall-2"], "openings": ["window-3", "door-4"], "confidence": 0.92 }',
  'List boundaryWalls and openings SEPARATELY (never mix walls and openings in one array).',
  '',
  '5. TOPOLOGY SUMMARY (topologySummary):',
  'Return a normalized summary: { "continuousWalls": [], "corners": [], "tJunctions": [], "falsePositives": [] } — all IDs must come from the RAW recognition result. No invented IDs.',
  'In addition to the detailed arrays, return a compact summary. It may contain ONLY IDs present in RAW JSON.',
  '{ "continuousWalls": [["wall-3", "wall-1"]], "corners": [["wall-3", "wall-2"]], "tJunctions": [["wall-3", "wall-2"]], "falsePositives": ["window-1"] }',
  '- continuousWalls: groups of wall IDs that are one continuous straight wall run (same semantics as wallRelationships same_continuous_wall).',
  '- corners: wall-ID pairs meeting at a corner.',
  '- tJunctions: wall-ID pairs meeting at a T-junction.',
  '- falsePositives: single IDs classified as likely_false_positive.',
  '',
  '6. GEOMETRY CONSTRAINTS (geometryConstraints):',
  'You are NOT being asked to redraw the floorplan and you are NOT a geometry solver.',
  'Your job is to INSPECT (1) the original floorplan image, (2) the RAW recognition polygons, (3) the object IDs, and (4) the existing object geometry — and to identify geometric relationships and corrections that a FUTURE DETERMINISTIC GEOMETRY SOLVER could later apply.',
  'You propose CONSTRAINTS, never geometry. Each constraint references only existing RAW object IDs and describes a relationship or correction that can eventually be implemented deterministically.',
  'Each constraint: { "type": "<one_of_ten>", "objectIds": ["<raw-id>", ...], "confidence": 0.0-1.0, "reason": "<string or null>" }.',
  'Allowed types (exactly these ten):',
  '- merge_walls: 2+ RAW wall objects should be treated as one logical wall entity (fragmented detection of one physical wall).',
  '- continue_wall: objectIds[0] and objectIds[1] are detections of the SAME physical wall; the wall continues from the first toward the second. ORDER MATTERS — first is the source, second is the continuation target.',
  '- extend_wall: objectIds[0] appears truncated and should be extended until it reaches objectIds[1] (the target/intersecting wall). ORDER MATTERS — first is the source to extend, second is the target.',
  '- remove_object: the referenced object(s) do not represent architecture (false positive) and should be removed. A single objectId is allowed.',
  '- parallel_walls: the referenced walls are visually parallel.',
  '- perpendicular_walls: the referenced walls are visually perpendicular.',
  '- same_axis: the referenced walls appear collinear on the same geometric axis.',
  '- wall_corner: the referenced walls meet at a corner.',
  '- wall_t_junction: the referenced walls meet at a T-junction.',
  '- opening_interrupts_wall: objectIds[0] is an opening (door/window/entry_door) that interrupts objectIds[1] (its host wall). ORDER MATTERS — first is the opening, second is the host wall.',
  'CRITICAL GEOMETRY CONSTRAINT RULES:',
  '- Never invent coordinates, never estimate pixel coordinates, never redraw walls, never replace RAW geometry.',
  '- Never output coordinates, polygon vertices, x/y values, lengths, thicknesses, or dimensions.',
  '- Only reference existing RAW object IDs — invalid IDs are filtered out server-side. Never invent IDs.',
  '- Only create a constraint when there is clear visual evidence in the source image.',
  '- Prefer "uncertain" / LOW CONFIDENCE over unsupported assumptions. If unsure, lower the confidence or omit the constraint.',
  '- A constraint must describe a relationship or correction that can eventually be implemented deterministically.',
  '- Do not use room semantics as a substitute for geometry.',
  '- Do not assume two objects are related merely because they are close.',
  '- Treat furniture, stairs, text, symbols and decorative graphics as possible recognition contamination.',
  '- The JSON must contain the geometry constraint itself (e.g. { "type": "merge_walls", "objectIds": ["wall-0", "wall-4"], ... }), NOT prose observations. Put the human-readable justification in reason.',
  '- Do not calculate exact missing lengths yet, and do not modify coordinates. First we validate the quality of the semantic/geometric constraints.',
  'Give special attention to:',
  '- fragmented walls (one physical wall split into multiple RAW objects)',
  '- continuous walls interrupted by doors/windows',
  '- walls that should meet at corners',
  '- T-junctions',
  '- truncated wall segments',
  '- parallel walls',
  '- perpendicular walls',
  '- false-positive wall/window detections',
  '- openings interrupting otherwise continuous walls',
  'TOPOLOGY vs CONSTRAINT: wallRelationships/topologySummary = architectural interpretation. geometryConstraints = actionable relationships for a future deterministic solver. Keep the two concepts separate. If an existing topology relationship can directly produce a geometry constraint, you MAY emit the corresponding constraint, but do not duplicate information unnecessarily.',
  '',
  'ARCHITECTURAL REASONING STYLE:',
  'Distinguish architectural truth from recognition artifacts. Example reasoning:',
  'RAW: wall-3 and wall-1 are two polygons. ARCHITECTURAL INTERPRETATION: two detections of one continuous facade. CONSTRAINTS: merge_walls or continue_wall.',
  'RAW: window-1 is a diagonal polygon. ARCHITECTURAL INTERPRETATION: likely false positive. CONSTRAINTS: remove_object.',
  'RAW: wall-4 is a large multi-segment polygon. ARCHITECTURAL INTERPRETATION: potentially contaminated by stair graphics; geometry should not be trusted as-is.',
  '',
  'PRESERVE UNCERTAINTY:',
  '- Never force a relationship. If you cannot reliably determine it, use "uncertain", lower the confidence, and explain why in reason.',
  '- Do not hallucinate topology.',
  '- Confidence must combine BOTH architectural confidence AND object-ID grounding confidence. If architecture is clear but the ID is ambiguous, keep confidence low.',
  '',
  'FORMAT:',
  '- Every array (wallRelationships, openings, objectClassifications, rooms) must be present — use empty array [] if no findings. topologySummary and geometryConstraints must always be present (use [] if no constraints).',
  '- Every relationship/classification/constraint needs a confidence 0.0-1.0 and a reason (string or null).',
  '- Do not assume that sequential IDs represent spatial order (wall-0 next to wall-1 is not guaranteed).',
  '- Return ONLY the structured JSON. No prose outside the schema.',
].join('\n');

export type VlmUserContentPart =
  | { type: 'text'; text: string }
  | { type: 'image_url'; image_url: { url: string } };

export function buildVlmUserMessage(params: {
  imageBuffer: Buffer;
  mimeType: string;
  raw: RawFloorplanRecognitionResponse;
  annotatedImageBuffer?: Buffer;
  annotatedMimeType?: string;
}): VlmUserContentPart[] {
  const rawSummary = {
    wall: params.raw.wall.length,
    door: params.raw.door.length,
    entry_door: params.raw.entry_door.length,
    window: params.raw.window.length,
    kitchen: params.raw.kitchen.length,
    door_center_line: params.raw.door_center_line.length,
    entry_door_center_line: params.raw.entry_door_center_line.length,
    window_center_line: params.raw.window_center_line.length,
  };

  const rawJsonStr = JSON.stringify(params.raw, null, 2);
  const hasAnnotated = !!params.annotatedImageBuffer;

  return [
    {
      type: 'text',
      text: [
        hasAnnotated
          ? 'You are analyzing a floorplan using THREE inputs: the ORIGINAL image, the ANNOTATED RECOGNITION image, and the RAW JSON.'
          : 'SOURCE IMAGE: floor plan image attached.',
        '',
        hasAnnotated ? 'IMAGE 1 = ORIGINAL FLOORPLAN: use ONLY for architectural interpretation (real walls, room semantics, false positives).' : '',
        hasAnnotated ? 'IMAGE 2 = ANNOTATED RECOGNITION: overlays with IDs (wall-0, window-2, etc.) — use ONLY to ground object IDs.' : '',
        hasAnnotated ? 'RAW JSON = exact object data: use for exact IDs, exact polygon data, verification.' : '',
        '',
        `RAW RECOGNITION SUMMARY: ${JSON.stringify(rawSummary)}`,
        '',
        'RAW RECOGNITION JSON (machine-detected objects, coordinates in image pixels):',
        rawJsonStr,
        '',
        hasAnnotated
          ? 'Use IMAGE 1 for architecture, IMAGE 2 for ID grounding, RAW JSON for exact IDs. Every ID you reference MUST appear in the RAW JSON. If unsure about an ID, use relationship/classification "uncertain" with low confidence — never guess an ID.'
          : 'Analyze wall continuity, opening->wall associations, object classification, room semantics, and produce the topology summary.',
        'Reference IDs like wall-0, wall-1, window-2, door-0, entry_door-0, kitchen-0.',
        'The image shows the true architecture; the JSON is noisy machine detection.',
        '',
        'Pay special attention to:',
        '- East exterior wall (interrupted by window, split into multiple wall segments) — which wall IDs form it? (wall-3 + wall-1?)',
        '- Which wall(s) host window-2? (east facade)',
        '- Kitchen boundary: which wall objects enclose the kitchen?',
        '- Hallway / circulation boundaries.',
        '- window-1 as a likely false positive (diagonal polygon overlapping furniture).',
        '- Wall geometry contaminated by stair graphics (e.g. wall-4) — mark suspicious instead of valid.',
        '',
        'RAW geometry is incomplete/noisy and may contain fragmented walls, missing segments, duplicate wall segments, false positives, incorrect classifications, openings interrupting walls, and small geometric artifacts. Use the image to determine which RAW objects are truly related — do NOT blindly trust RAW geometry.',
        '',
        'GEOMETRY CONSTRAINTS — propose deterministic, actionable constraints for a future solver (never coordinates, never replacement geometry):',
        '- Look for visually continuous walls split into multiple RAW objects → merge_walls or continue_wall.',
        '- Look for parallel walls (opposing or aligned segments) → parallel_walls.',
        '- Look for perpendicular walls meeting at right angles → perpendicular_walls or wall_corner.',
        '- Look for collinear/same-axis walls → same_axis.',
        '- Look for walls that appear truncated and should meet another wall → extend_wall (first ID = source to extend, second = target).',
        '- Look for walls meeting at corners or T-junctions → wall_corner / wall_t_junction.',
        '- Look for doors/windows interrupting otherwise continuous walls → opening_interrupts_wall (first ID = opening, second = host wall).',
        '- Look for false-positive detections (furniture, stairs, text, symbols, decorative graphics) → remove_object.',
        '- Only create a constraint when there is visual evidence in the source image. Prefer low confidence over unsupported assumptions. Never invent IDs, coordinates or lengths.',
        '- The VLM is proposing constraints, not constructing geometry.',
        '',
        'Return the topology JSON structure only.',
      ]
        .filter(Boolean)
        .join('\n'),
    },
    {
      type: 'image_url',
      image_url: { url: `data:${params.mimeType};base64,${params.imageBuffer.toString('base64')}` },
    },
    ...(hasAnnotated && params.annotatedImageBuffer
      ? [
          {
            type: 'image_url' as const,
            image_url: {
              url: `data:${params.annotatedMimeType ?? 'image/png'};base64,${params.annotatedImageBuffer.toString('base64')}`,
            },
          },
        ]
      : []),
  ];
}
