apiVersion: v1
kind: Secret
metadata:
  name: vista-expose-service-secrets
type: Opaque
stringData:
  OPENAI_API_KEY: "replace-me"
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/vista"
  CLOUDFLARE_S3_API_ENDPOINT: "replace-me"
  CLOUDFLARE_ACCESS_KEY_ID: "replace-me"
  CLOUDFLARE_SECRET_ACCESS_KEY: "replace-me"
  CLOUDFLARE_R2_BUCKET: "replace-me"
