global:
  imagePullSecrets:
    - name: gitlab-registry

replicaCount: ${VISTA_NATS_REPLICAS}

nameOverride: "nats"

image:
  repository: "${NATS_IMAGE_REPOSITORY}"
  tag: "${NATS_IMAGE_TAG}"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  clientPort: 4222
  monitorPort: 8222

jetstream:
  enabled: true

surveyor:
  replicaCount: ${VISTA_NATS_SURVEYOR_REPLICAS}
  image:
    repository: "${NATS_SURVEYOR_IMAGE_REPOSITORY}"
    tag: "${NATS_SURVEYOR_IMAGE_TAG}"
    pullPolicy: IfNotPresent
  servers: "${NATS_SURVEYOR_SERVERS}"
  serverCount: ${NATS_SURVEYOR_SERVER_COUNT}
  service:
    type: ClusterIP
    port: 7777
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi